---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)

library(tidyverse)
library(haven)
library(dplyr)
library(ggplot2)
library(pollster)
library(knitr)
library(corrplot)
library(Hmisc)
library(nnet)
library(stargazer)
library(MASS)
library(broom)
library(plotly)

```

Column {data-width=650}
-----------------------------------------------------------------------

### Chart A

```{r}
# uploading data
ccamData <- read_sav("CCAMData2023.sav")

myData <- ccamData %>%
  dplyr::select(wave, year, happening, cause_recoded, worry, harm_personally, harm_US, harm_future_gen, harm_plants_animals, when_harm_US,
                region9, generation, educ_category) %>% 
  rename("education" = "educ_category") 

# subsetting with data for the last available wave, Oct 2023
myData <- subset(myData, wave == 29)

# making variables numeric or factors
myData$wave <- as.numeric(myData$wave)
myData$happening <- as.factor(myData$happening)
myData$cause_recoded <- as.factor(myData$cause_recoded)
myData$generation <- as.factor(myData$generation)
myData$education <- as.factor(myData$education)
myData$worry <- as.numeric(myData$worry)
myData$harm_personally <- as.factor(myData$harm_personally)
myData$harm_US <- as.factor(myData$harm_US)
myData$harm_future_gen <- as.factor(myData$harm_future_gen)
myData$harm_plants_animals <- as.factor(myData$harm_plants_animals)
myData$when_harm_US <- as.factor(myData$when_harm_US)
myData$region9 <- as.factor(myData$region9)

# recoding variables
myData <- myData %>%
  mutate(#year = recode(year, "13" = "2021"),
         
         wave = recode(wave, "29" = "Oct 2023"),
         
         cause_recoded = recode(cause_recoded, "3" = "CC_not_happening", "4" = "Nat_changes", "5" = "Human_act_and_nat_changes",
                                "6" = "human_act"),
         
         happening = recode(happening, "1" = "No", "3" = "Yes"),
         
         harm_personally = recode(harm_personally, "1" = "Not at all", "2" = "Only a little", "3" = "A moderate amount", "4" = "A great deal"),
         
         harm_US = recode(harm_US, "1" = "Not at all", "2" = "Only a little", "3" = "A moderate amount", "4" = "A great deal"),
         
         harm_future_gen = recode(harm_future_gen, "1" = "Not at all", "2" = "Only a little", "3" = "A moderate amount", "4" = "A great deal"),
         
         harm_plants_animals = recode(harm_plants_animals, "1" = "Not at all", "2" = "Only a little", "3" = "A moderate amount",
                                      "4" = "A great deal"),
         
         when_harm_US = recode(when_harm_US, "1" = "Never", "2" = "one_hun_years", "3" = "fifty_years", "4" = "twn_five_years",
                               "5" = "ten_years", "6" = "right_now"),
         
         region9 = recode(region9, "1" = "New England", "2" = " Mid_Atlantic", "3" = "EN_Central", "4" = "WN_Central", "5" = "S_Atlantic",
                          "6" = "ES_Central", "7" = "WS_Central", "8" = "Mountain", "9" = "Pacific"),

         
         generation = recode(generation, "1" = "GenZ", "2" = "Millennials", "3" = "GenerationX", "4" = "BabyBoomers", "5" = "Silent",
                             "6" = "Greatest"),
         
         education = recode(education, "1" = "lessHighSchool", "2" = "highSchool", "3" = "someCollege", "4" = "bachelorDegreeUp"))

# getting rid of data where people refused to answer (-1) or said they "don't know" (0)
myData = filter(myData, !(cause_recoded %in% c("-1", "1", "2")))
myData = filter(myData, worry != "-1")
myData = filter(myData, !(happening %in% c("-1", "2"))) # 2 is "don't know"
myData = filter(myData, !(harm_personally %in% c("-1", "0")))
myData = filter(myData, !(harm_US %in% c("-1", "0")))
myData = filter(myData, !(harm_future_gen %in% c("-1", "0")))
myData = filter(myData, !(harm_plants_animals %in% c("-1", "0")))
myData = filter(myData, generation != "Greatest") # get rid of Greatest because they only had 1 respondent in 2021
myData = filter(myData, when_harm_US != "-1")

# creating the reference variable now
myData$happening <- relevel(myData$happening, ref = "No")
myData$education <- relevel(myData$education, ref = "lessHighSchool")
myData$cause_recoded <- relevel(myData$cause_recoded, ref = "Human_act_and_nat_changes")
myData$harm_personally <- relevel(myData$harm_personally, ref = "Not at all")
myData$harm_US <- relevel(myData$harm_US, ref = "Not at all")
myData$harm_future_gen <- relevel(myData$harm_future_gen, ref = "Not at all")
myData$harm_plants_animals <- relevel(myData$harm_plants_animals, ref = "Not at all")
myData$when_harm_US <- relevel(myData$when_harm_US, ref = "Never")


```


```{r}

wPersonally <- myData %>%
  group_by(harm_personally) %>% 
  mutate(per_count = n()) %>% 
  group_by(harm_personally, worry) %>% 
  mutate(worry = recode(worry,
                        "1" = "Not at all worried",
                        "2" = "Not very worried",
                        "3" = "Somewhat worried",
                        "4" = "Very worried")) %>% 
  summarise(count = n(),
            percentage = round((count / first(per_count)) * 100)) %>% 
  ungroup()

#wCause[nrow(wCause) + 1,] <- list("Climate Change Not Happening", "Very worried", 0, 0)

wPersonally <- data.frame(wPersonally)

g <- ggplot(wPersonally, aes(x = harm_personally, y = percentage)) +
  geom_bar(stat = "identity", fill = "#3B1E54") +
  labs(title = "Worry of Climate Change by Belief of Personal Harm", x = "Personal Harm", y = "Percentage") +
  theme_bw() +
  facet_wrap(~worry) +
  coord_flip()

p <- ggplotly(g)

p

```

Column {data-width=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

